modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
displayName = "${mod_name}"
version = "${mod_version}"
authors = "${mod_authors}"
description="${mod_description}"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}_forge.mixins.json"

file = "META-INF/accesstransformer.cfg"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "AFTER"
side = "BOTH"